rmdir /S /Q AutoUpdater\bin
rmdir /S /Q AutoUpdater\obj
rmdir /S /Q Communication\bin
rmdir /S /Q Communication\obj
rmdir /S /Q Patterns\bin
rmdir /S /Q Patterns\obj
rmdir /S /Q PoL.Common\bin
rmdir /S /Q PoL.Common\obj
rmdir /S /Q PoL.Configuration\bin
rmdir /S /Q PoL.Configuration\obj
rmdir /S /Q PoL.Logic\bin
rmdir /S /Q PoL.Logic\obj
rmdir /S /Q PoL.Models\bin
rmdir /S /Q PoL.Models\obj
rmdir /S /Q PoL.Server\bin
rmdir /S /Q PoL.Server\obj
rmdir /S /Q PoL.Services\bin
rmdir /S /Q PoL.Services\obj
rmdir /S /Q PoL.Test\bin
rmdir /S /Q PoL.Test\obj
rmdir /S /Q PoL.WinFormsView\bin
rmdir /S /Q PoL.WinFormsView\obj
rmdir /S /Q RibbonStyle\bin
rmdir /S /Q RibbonStyle\obj